version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "angularjs",
    "meteor",
    "angular"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/kushan265/nand2tetris"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "scalafmt"
enabled = true